services:
  web:
    build: .
    container_name: tp_flask
    ports:
      - "5002:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017
    depends_on:
      - mongo

  mongo:
    image: mongo:7
    container_name: tp_mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: